### ISSUE TITLE
Update to Angular v15

### ISSUE THREAD

**Issue by masihsadatyyc** [hakimio/ngx-ui-tour#91]
I like to point out this works perfectly fine for ng14.

I tried to do a temporary manual workaround by copying this library directly into the project and noticed that matMenuTriggerFor didn't work but I noticed you changed this recently.

I keep getting the following message:
'Can't attach to unregistered anchor with id '

I believe this part seems to be causing issues when using ng15.
"<span matMenuTriggerFor [matMenuTriggerRestoreFocus]="false"></span>"

Thanks again for this library :)

**Comment by hakimio** [comment]
Here is the new `Angular Material v15` step template for those who can't wait for `ngx-ui-tour v10` release to start using `Angular v15` with `Angular Material v15` components.

![new step template](https://user-images.githubusercontent.com/768105/207554066-57f5795e-c55a-4cda-9815-11e3130950a9.PNG)

`tour-step.component.html`
```html
<mat-card (click)="$event.stopPropagation()">
    <mat-card-header>
        <div class="header-group">
            <mat-card-title>
                {{step.title}}
            </mat-card-title>
            <button
                mat-icon-button
                (click)="tourService.end()"
                class="close"
            >
                <mat-icon>close</mat-icon>
            </button>
        </div>
    </mat-card-header>

    <mat-card-content
        class="mat-body"
        [innerHTML]="step.content"
    ></mat-card-content>

    <mat-card-actions align="end">
        <button
            mat-button
            class="prev"
            [disabled]="!tourService.hasPrev(step)"
            (click)="tourService.prev()"
        >
            <mat-icon>chevron_left</mat-icon>
            {{step.prevBtnTitle}}
        </button>
        <button
            class="next"
            *ngIf="tourService.hasNext(step) && !step.nextOnAnchorClick"
            (click)="tourService.next()"
            mat-button
        >
            {{step.nextBtnTitle}}
            <mat-icon iconPositionEnd>chevron_right</mat-icon>
        </button>
        <button
            mat-button
            (click)="tourService.end()"
            *ngIf="!tourService.hasNext(step)"
        >
            {{step.endBtnTitle}}
        </button>
    </mat-card-actions>
</mat-card>
```
`tour-step.component.scss`
```scss
@use '@angular/material' as mat;

:host {
    @include mat.icon-button-density(-2);
}

::ng-deep .tour-step .mat-mdc-menu-content {
    padding: 0 !important;
}

mat-card {
    min-width: 200px;
}

mat-card-content {
    margin: 8px 0;
}

mat-card-actions {
    justify-content: space-between;

    button.prev {
        padding-left: 4px;
    }

    button.next {
        padding-right: 4px;
    }
}

mat-card-header {
    .header-group {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-top: -8px;
        width: 100%;

        mat-card-title {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        button {
            margin-right: -8px;
        }
    }
}
```
`tour-step.component.ts`
```ts
import {Component, inject, Input} from '@angular/core';
import {IStepOption, TourService} from 'ngx-ui-tour-md-menu';
import {MatCardModule} from '@angular/material/card';
import {MatButtonModule} from '@angular/material/button';
import {NgIf} from '@angular/common';
import {MatIconModule} from '@angular/material/icon';

@Component({
    selector: 'app-tour-step',
    templateUrl: './tour-step.component.html',
    styleUrls: ['./tour-step.component.scss'],
    imports: [
        MatCardModule,
        MatButtonModule,
        MatIconModule,
        NgIf
    ],
    standalone: true
})
export class TourStepComponent {

    @Input()
    step!: IStepOption;

    tourService = inject(TourService);

}
```
`app.component.html`
```html
<!-- ... -->
<tour-step-template>
    <ng-template let-step="step">
        <app-tour-step
            [step]="step"
        ></app-tour-step>
    </ng-template>
</tour-step-template>
```

### Demo project
[ui-tour-ng-material-v15.zip](https://github.com/hakimio/ngx-ui-tour/files/10226229/ui-tour-ng-material-v15.zip)
